name: PluginName
main: Example\Main
version: "1.0.0"
api: [1.12.0]
author: PMPlugins
description: 

commands:
 example:
  aliases: [exmp]
  description: 
  permission: example

permissions:
 example:
  default: op
  description: 
  children:
   example.help:
    default: op
    description: 
